### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by MintyMods** [PikadudeNo1/svelte-writable-derived#3]
Does the following extract from "Default export: writableDerived()" contain a typo (and should read "It is `now` possible" rather than `not possible`)?

> It is not possible for derived and reflect to trigger calls to each other, provided they only use the set callbacks provided to them and do not reach out to any outer set or update.

**Comment by PikadudeNo1** [comment]
No, it's meant to be "not". This sentence is your assurance that your derive and reflect callbacks cannot go into an infinite loop of calling each other.

**Comment by MintyMods** [comment]
Thank you for the clarification.

**Comment by PikadudeNo1** [comment]
No problem.
